export const DONATION_TAG_LINES: string[] = [
  "Sedikit memberi, banyak mengubah.",
  "Setiap rupiah berarti.",
  "Donasi Anda, harapan mereka.",
  "Bersama, kita bisa membuat perbedaan.",
  "Jadilah alasan seseorang tersenyum hari ini.",
  "Tindakan kecil, dampak besar.",
  "Kebaikan kecil membawa perubahan besar.",
  "Ulurkan tangan, ubah kehidupan.",
  "Kebaikan dimulai dari diri sendiri.",
  "Jadikan memberi sebagai kebiasaan.",
  "Memberi adalah investasi untuk masa depan.",
  "Berbagi kebahagiaan dengan sesama.",
  "Sedekah takkan membuatmu miskin.",
  "Kebaikanmu adalah berkah bagi orang lain.",
  "Jangan menunggu kaya untuk berbagi.",
  "Satu donasi, sejuta manfaat.",
  "Cahaya kehidupan dimulai dari kepedulian.",
  "Jadilah pahlawan bagi yang membutuhkan.",
  "Saat kita berbagi, kita peduli.",
  "Donasi kecil, perubahan besar.",
  "Jadilah bagian dari perubahan.",
  "Bantu sesama, bahagiakan dunia.",
  "Kita kuat jika kita peduli.",
  "Kebahagiaan sejati adalah berbagi.",
  "Berbagi bukan tentang seberapa banyak yang kamu punya.",
  "Memberi dengan hati, bukan dengan jumlah.",
  "Satu tangan memberi, sejuta hati menerima.",
  "Harapan baru lahir dari kebaikan.",
  "Bantu mereka yang tak seberuntung kita.",
  "Saling menolong adalah tugas kita sebagai manusia.",
  "Menolong sesama adalah bentuk cinta kasih.",
  "Cintai sesama dengan berbagi.",
  "Kepedulian adalah langkah pertama menuju perubahan.",
  "Satu kebaikan menciptakan ribuan inspirasi.",
  "Mari bersama ciptakan dunia yang lebih baik.",
  "Jangan ragu untuk berbagi.",
  "Kebersamaan dimulai dari berbagi.",
  "Jadilah sumber inspirasi dengan memberi.",
  "Donasi adalah bentuk kepedulian nyata.",
  "Saat kamu memberi, kamu mendapat lebih banyak.",
  "Bantu hari ini untuk masa depan yang lebih baik.",
  "Sedekah membuka pintu keberkahan.",
  "Kebaikan adalah investasi yang tak ternilai.",
  "Bersama, kita bisa mengubah dunia.",
  "Mereka butuh kita, mari bantu mereka.",
  "Jangan biarkan mereka berjuang sendirian.",
  "Jadilah pelita di tengah kegelapan.",
  "Satu tindakan baik dapat mengubah hidup seseorang.",
  "Mari berbagi dengan penuh cinta.",
  "Kebahagiaan sejati datang dari memberi.",
  "Berbagi rezeki, berbagi kebahagiaan.",
  "Saat kamu memberi, kamu pun diberkahi.",
  "Jadilah bagian dari kebaikan tanpa batas.",
  "Donasi adalah bentuk cinta kepada sesama.",
  "Tidak ada yang sia-sia dalam berbagi.",
  "Setetes kepedulian, lautan perubahan.",
  "Dari tangan kita, harapan mereka hidup.",
  "Masa depan cerah dimulai dengan berbagi.",
  "Mari tebarkan kebaikan kepada dunia.",
  "Berbuat baik itu mudah, ayo mulai sekarang!",
  "Ulurkan tanganmu, ringankan beban mereka.",
  "Mari jadikan dunia tempat yang lebih baik.",
  "Sedekah membuka pintu kebahagiaan.",
  "Hidup lebih bermakna saat kita berbagi.",
  "Jangan tunggu nanti, berbagi sekarang.",
  "Satu hati, sejuta harapan.",
  "Kita kuat saat kita saling peduli.",
  "Berbagi dengan ikhlas, hidup jadi berkah.",
  "Donasi adalah jembatan menuju harapan baru.",
  "Menolong adalah bentuk rasa syukur.",
  "Jangan biarkan kesulitan menghentikan senyum mereka.",
  "Satu langkah kecil, perubahan besar terjadi.",
  "Kebaikan sekecil apapun tetap berarti.",
  "Kebaikan adalah investasi jangka panjang.",
  "Jadilah bagian dari solusi, bukan hanya penonton.",
  "Saat kita berbagi, kita tumbuh bersama.",
  "Sedekah adalah tabungan untuk akhirat.",
  "Setiap rupiah yang kamu beri, menyelamatkan hidup.",
  "Kita tidak bisa membantu semua orang, tapi semua orang bisa membantu seseorang.",
  "Berbagi adalah wujud nyata kepedulian kita.",
  "Mari bergerak bersama untuk kebaikan.",
  "Tindakan kecil dapat mengubah dunia.",
  "Kita berbagi karena kita peduli.",
  "Donasi hari ini, perubahan untuk selamanya.",
  "Mereka membutuhkan uluran tanganmu.",
  "Dukung mereka yang membutuhkan dengan sepenuh hati.",
  "Senyum mereka adalah hadiah terbesar.",
  "Mari berbagi kebahagiaan dengan mereka yang membutuhkan.",
  "Saat kita berbagi, kita membuat dunia lebih baik.",
  "Bersama kita bisa mengubah masa depan mereka.",
  "Kebaikan itu menular, mari sebarkan!",
  "Tak perlu kaya untuk berbagi, cukup dengan hati.",
  "Donasi bukan tentang jumlah, tapi tentang keikhlasan.",
  "Kecil bagi kita, besar bagi mereka.",
  "Bantu satu orang, ubah dunia.",
  "Setiap orang berhak mendapat kesempatan yang lebih baik.",
  "Memberi tanpa mengharap kembali adalah kebaikan sejati.",
  "Mari jadikan berbagi sebagai gaya hidup.",
  "Bantu mereka untuk berdiri kembali.",
  "Kita hidup untuk saling membantu.",
  "Ciptakan keajaiban melalui kebaikan.",
  "Jadilah jawaban atas doa seseorang.",
  "Tak perlu menunggu momen yang sempurna untuk berbagi.",
  "Donasi Anda adalah cahaya bagi mereka.",
  "Ayo bergerak bersama untuk masa depan yang lebih cerah.",
  "Setiap orang bisa menjadi pahlawan dengan berbagi.",
  "Jangan ragu untuk menolong mereka yang membutuhkan.",
  "Jadilah perpanjangan tangan Tuhan dalam berbagi.",
  "Setiap hati yang peduli membawa perubahan.",
  "Ayo wujudkan impian mereka bersama-sama.",
  "Satu hati, satu dunia, satu kepedulian.",
  "Pendidikan",
  "Kesehatan",
  "Wanita",
  "Social",
  "Natural",
];
