export const DONATION_TAG_LINES: string[] = [
  "Bencana",
  "Social",
  "Education",
  "Pendidikan",
  "Women",
  "Wanita",
  "Natural",
  "Alam",
  "Bantuan",
  "Solidaritas",
  "Kemanusiaan",
  "Kepedulian",
  "Pertolongan",
  "Kasih Sayang",
  "Empati",
  "Gotong Royong",
  "Harapan",
  "Peduli Sesama",
  "Kesejahteraan",
  "Perubahan",
  "Keikhlasan",
  "Uluran Tangan",
  "Bakti Sosial",
  "Cinta Kasih",
  "Relawan",
  "Kebersamaan",
  "Kesetaraan",
  "Kesejahteraan Sosial",
  "Dukungan",
  "Kedermawanan",
  "Kebajikan",
  "Keberkahan",
  "Kepercayaan",
  "Aksi Sosial",
  "Kesetiakawanan",
  "Tolong-Menolong",
  "Pelayanan",
  "Kesejahteraan Bersama",
  "Kemanusiaan Universal",
  "Harapan Baru",
  "Cahaya Kebaikan",
  "Kepedulian Sosial",
  "Aksi Nyata",
  "Misi Kemanusiaan",
  "Donasi Peduli",
  "Dampak Positif",
  "Kesadaran Sosial",
  "Kebersamaan Abadi",
  "Gerakan Sosial",
  "Kepedulian Lingkungan",
  "Saling Berbagi",
  "Kebahagiaan Bersama",
  "Pertolongan Cepat",
  "Tangan Terbuka",
  "Hati Dermawan",
  "Cinta Tanpa Batas",
  "Perjuangan Bersama",
  "Komunitas Peduli",
  "Keseimbangan Sosial",
  "Kasih Sesama",
  "Langkah Kebaikan",
  "Bantuan Tanpa Syarat",
  "Empati Tanpa Batas",
  "Uluran Kasih",
  "Dukung Bersama",
  "Kepedulian Murni",
  "Kedermawanan Hakiki",
  "Kebaikan Universal",
  "Semangat Gotong Royong",
  "Tindakan Peduli",
  "Kebaikan Bersama",
  "Harapan Sesama",
  "Kekuatan Kebersamaan",
  "Komitmen Sosial",
  "Kontribusi Nyata",
  "Bantu Saudara",
  "Pahlawan Kemanusiaan",
  "Gerakan Berbagi",
  "Tindakan Nyata",
  "Bakti Masyarakat",
  "Inspirasi Peduli",
  "Aksi Peduli",
  "Solidaritas Global",
  "Cahaya Harapan",
  "Senyum Bersama",
  "Masyarakat Berdaya",
  "Saling Menjaga",
  "Keseimbangan Hidup",
  "Kasih Tanpa Pamrih",
  "Aksi Bersama",
  "Tangan Kasih",
  "Saling Menguatkan",
  "Dukung dan Bangkit",
  "Perubahan Sosial",
  "Kebangkitan Bersama",
  "Kebahagiaan untuk Semua",
  "Kemanusiaan Tanpa Batas",
  "Gerakan Peduli Sesama",
  "Senyum Peduli",
  "Kedermawanan Sejati",
  "Pengorbanan Mulia",
  "Langkah Kecil Dampak Besar",
  "Kebaikan Hati",
  "Berdaya Bersama",
  "Persatuan dan Kepedulian",
  "Kesejahteraan Tanpa Batas",
  "Kemanusiaan Tulus",
  "Kepekaan Sosial",
  "Harmoni Sosial",
  "Gotong Royong Nasional",
  "Kedermawanan Nusantara",
  "Solidaritas Tanpa Batas",
  "Perhatian Sosial",
  "Komunitas Sosial",
  "Aksi Kemanusiaan",
  "Keberagaman Peduli",
  "Bakti untuk Negeri",
  "Kasih dan Sayang",
  "Pengorbanan Suci",
  "Kesejahteraan Global",
  "Tangan untuk Sesama",
  "Kebaikan yang Menyelamatkan",
  "Menebar Kebaikan",
  "Gerakan Harapan",
  "Kekuatan Empati",
  "Harapan Hidup",
  "Perubahan Bersama",
  "Kehangatan Sosial",
  "Aksi Kepedulian",
  "Kebersamaan Kuat",
  "Semangat Berbagi",
  "Bakti Tanpa Batas",
  "Bersatu untuk Kebaikan",
  "Misi Sosial",
  "Menyebarkan Kasih",
  "Berbagi Berkah",
  "Bersama Menguatkan",
  "Memberi dan Berbagi",
  "Langkah Bersama",
  "Kebajikan Tanpa Batas",
  "Semangat Kemanusiaan",
  "Harapan untuk Semua",
  "Gerakan Kebaikan",
  "Kasih Tulus",
  "Dukung yang Membutuhkan",
  "Berbagi Cinta",
  "Tindakan Mulia",
  "Kesetiakawanan Sosial",
  "Peran Sosial",
  "Uluran Tangan Ikhlas",
  "Harapan Baru untuk Dunia",
  "Donasi yang Mengubah",
  "Cahaya Kehidupan",
  "Persaudaraan Sejati",
  "Donation",
];
