import "./globals.css";
import type { Metadata } from "next";
import ClientProvider from "@/components/ClientProvider";
import { Montserrat, Raleway, Roboto_Slab } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  style: ["normal"],
});

const raleway = Raleway({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Online donation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${robotoSlab.className} ${raleway.className}`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
