import "./globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import TanstackQueryProvider from "@/components/TanstackQueryProvider";
import { Montserrat, Raleway, Roboto_Slab } from "@next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  style: ["normal"],
});

const raleway = Raleway({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${robotoSlab.className} ${raleway.className}`}
      >
        <AuthProvider>
          <TanstackQueryProvider>{children}</TanstackQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
