import "./globals.css";
import type { Metadata } from "next";
import ClientProvider from "@/components/ClientProvider";
import { Montserrat, Raleway, Roboto_Slab } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const robotoslab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Online donation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${robotoslab.variable} ${raleway.variable}`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
